src/api/urls.py
from django.urls import path

from . import views


urlpatterns = [
     # Quiz actions
     path(
          'quiz/<slug:slug>/delete/',
          views.QuizDeleteAPI.as_view(),
          name="quiz-delete-api"
     ),
     path(
          'quiz/like-unlike/', 
          views.QuizLikeUnlikeAPI.as_view(),
          name="quiz-like-unlike-api"
     ),
     path(
          'quiz/<slug:slug>/comment/create/',
          views.CommentCreateAPI.as_view(),
          name="comment-create-api"
     ),
     path(
          'quiz/comment/delete/<int:pk>/',
          views.CommentDeleteAPI.as_view(),
          name="comment-delete-api"
     ),
     path(
          'quiz/bookmark/create-remove/',
          views.CreateRemoveBookmarkAPI.as_view(),
          name="bookmark-create-remove-api"
     ),
     path(
          'quiz/<slug:slug>/check-answer/',
          views.CheckAnswerAPI.as_view(),
          name="check-answer"
     ),
]

src/quiz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quizapp.urls')),
    path('users/', include('users.urls')),
    path('api/', include('api.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

src/quizapp/urls.py
from django.urls import path

from . import views


urlpatterns = [
     # Quiz lists
     path('', views.QuizList.as_view(), name="home"),
     path('most-viewed/', views.QuizListMostViewed.as_view(),
          name="most-viewed"),
     path('most-liked/', views.QuizListMostLiked.as_view(), name="most-liked"),
     path('user-quizzes/', views.QuizUserList.as_view(), name="user-quizzes"),

     # Quiz detail
     path('quiz/<slug:slug>/', views.QuizDetail.as_view(), name="quiz-detail"),

     # Quiz passing
     path(
          'quiz/<slug:slug>/passing/',
          views.QuestionList.as_view(
               template_name='quizapp/question_list.html',
               paginate_by=1
          ),
          name="question-list"
     ),
     path(
          'quiz/<slug:slug>/complete/',
          views.QuizComplete.as_view(),
          name="quiz-complete"
     ),

     # Manage questions
     path(
          'quiz/<slug:slug>/manage-questions/',
          views.QuestionList.as_view(
               template_name='quizapp/questions_manage.html',
               paginate_by=15
          ),
          name="manage-questions"
     ),

     # Create and delete a quiz
     path('create/quiz/', views.QuizCreate.as_view(), name="quiz-create"),
     path(
          'update/quiz/<slug:slug>/',
          views.QuizUpdate.as_view(),
          name="quiz-update"
     ),
]

src/quizapp/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.db.models import F

from .for_slug import slugify as my_slugify


LEVEL_CHOICES = [
    ('Легко', 'легко'),
    ('Средне', 'средне'),
    ('Сложно', 'сложно'),
    ('Экстремально', 'экстремально'),
]


class Quiz(models.Model):
    """Quiz model"""
    slug = models.SlugField(
        'Url-адрес',
        max_length=60,
        unique=True,
        db_index=True,
        blank=True
    )
    title = models.CharField('Название', max_length=50)
    body = models.TextField('Описание', blank=True)
    date = models.DateTimeField('Дата создания', auto_now_add=True)
    views = models.IntegerField('Просмотры', default=0)
    level = models.CharField('Уровень', max_length=20, choices=LEVEL_CHOICES)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='quizzes',
        verbose_name='Автор',
        blank=True,
        null=True
    )
    category = models.ForeignKey(
        'Category',
        on_delete=models.PROTECT,
        verbose_name='Категория',
        related_name='quiz',
        blank=True,
        null=True
    )
    likes = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        verbose_name="Понравилось",
        related_name="liked_quizzes",
        blank=True
    )
    photo = models.ImageField(
        'Фото',
        upload_to='main_quiz_photos/%Y/',
        blank=True,
        null=True
    )

    class Meta:
        verbose_name = 'Викторина'
        verbose_name_plural = 'Викторины'
        ordering = ['-date']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        """
        Use the custom slugify (for_slug.py) and add
        generated slug + self.id in self.slug
        """
        slug = my_slugify(self.title)
        self.slug = slug + f'-{self.id}'
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('quiz-detail', kwargs={'slug': self.slug})

    def get_update_url(self):
        return reverse('quiz-update', kwargs={'slug': self.slug})

    def get_question_list_url(self):
        return reverse('question-list', kwargs={'slug': self.slug})

    def get_manage_questions_url(self):
        return reverse('manage-questions', kwargs={'slug': self.slug})

    def get_likes_count(self):
        return self.likes.count()

    def get_completed_count(self):
        return QuizManager.objects.filter(quiz=self, completed=True).count()

    def get_comments_count(self):
        return self.comments.count()

    def get_bookmarks_count(self):
        return self.bookmarks.count()

    def get_questions_count(self):
        return self.questions.count()

    def get_bookmarks_users(self):
        """Return all users id who bookmarked the quiz"""
        users_id = []

        for bookmark in self.bookmarks.values('user'):
            users_id.append(bookmark['user'])

        return users_id

    def bookmark_quiz(self, quiz, user, bookmark):
        """Bookmark a quiz

        If bookmark is exists -> delete else create

        Args:
            quiz(obj): a quiz to be (un)bookmarked
            user(obj): a user who want to (un)bookmark the quiz
            bookmark(obj): a queryset to find a bookmark

        Returns:
            data(dict):
                bookmarked(bool): the quiz was bookmarked - True else False
                bookmarks(int): a count of all bookmarks at the quiz

        """
        data = {}

        if bookmark.exists():
            bookmark.delete()
            data['bookmarked'] = False
        else:
            Bookmark.objects.create(quiz=quiz, user=user)
            data['bookmarked'] = True

        data['bookmarks'] = quiz.get_bookmarks_count()

        return data

    def like_quiz(self, quiz, user):
        """Like a quiz

        If a user already liked the quiz -> remove it else add like

        Args:
            quiz(obj): a quiz to be (un)liked
            user(obj): a user who want to (un)like the quiz

        Returns:
            data(dict):
                liked(bool): quiz was liked - True else False
                likes(int): count of all likes at the quiz

        """
        data = {}

        if user in quiz.likes.all():
            quiz.likes.remove(user)
            data['liked'] = False
        else:
            quiz.likes.add(user)
            data['liked'] = True

        data['likes'] = quiz.get_likes_count()

        return data

    def increase_views(self):
        """Increase views field at the quiz"""
        self.views += 1
        self.save(update_fields=('views',))


class QuizManager(models.Model):
    """Manager for a quiz. NOT DJANGO MANAGER

    Important attributes:
        correct_answers(int): stores a count of correct answers.
        completed(bool): status of a quiz passing.
        passed(bool): if a quiz was passed ever -> True, default False

    """
    quiz = models.ForeignKey(
        Quiz,
        on_delete=models.CASCADE,
        related_name='managers',
        verbose_name='Викторина'
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='managers',
        verbose_name='Пользователь'
    )
    date = models.DateTimeField(
        'Дата создания', auto_now_add=True, blank=True, null=True
    )
    correct_answers = models.PositiveSmallIntegerField(
        'Правильные ответы',
        default=0
    )
    completed = models.BooleanField('Завершено', default=False)
    passed = models.BooleanField('Когда-либо пройдено', default=False)

    class Meta:
        verbose_name = 'Менеджер викторины'
        verbose_name_plural = 'Менеджеры викторин'

    def __str__(self):
        return f'{self.quiz}-{self.user}'

    def get_correct_answers(self):
        return self.correct_answers

    def increase_correct_answers(self):
        """Increase the correct_answers field"""
        self.correct_answers = F('correct_answers') + 1
        self.save(update_fields=('correct_answers',))

    def remove_correct_answers(self):
        """Set correct answers field as 0"""
        self.correct_answers = 0
        self.save(update_fields=('correct_answers',))

    def set_as_completed(self):
        """Set the completed field to True"""
        self.completed = True
        self.save(update_fields=('completed',))

    def set_as_uncompleted(self):
        """Set the completed field to False"""
        self.completed = False
        self.save(update_fields=('completed',))

    def set_as_passed(self):
        """Set the passed field to True"""
        self.passed = True
        self.save(update_fields=('passed',))

    def get_passing_status(self, quiz):
        """Return the quiz passing status.

        Calculate different between QuizManager.correct_answers count
        and quiz.questions couns. Set status as awesome, good, normal or bad

        Args:
            quiz(obj): quiz for checking

        Returns:
            status(str): result status of the passing

        """
        if self.correct_answers == quiz.get_questions_count():
            status = 'Потрясающе 😍'

        elif self.correct_answers > quiz.get_questions_count() / 1.5 and \
                self.correct_answers < quiz.get_questions_count():
            status = 'Отлично 👍'

        elif self.correct_answers > quiz.get_questions_count() / 2.5 and \
                self.correct_answers < quiz.get_questions_count() / 1.5:
            status = 'Неплохо 😁'

        else:
            status = 'Не огорчайся 😕'

        return status

    def calculate_required_xp_count(self, passing_status: str):
        """Calculate the required xp count

        Check passing_status and define xp_count
        depending on the passing status

        Args:
            passing_status(str): status of the quiz passing

        Returns:
            xp_count(int): the amount of xp needed to increase it

        """
        if passing_status == 'Потрясающе 😍':
            xp_count = 100
        elif passing_status == 'Отлично 👍':
            xp_count = 75
        elif passing_status == 'Неплохо 😁':
            xp_count = 50
        else:
            xp_count = 10

        return xp_count


class Category(models.Model):
    """Category for quizzes"""
    name = models.CharField('Имя категории', max_length=30)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


class Comment(models.Model):
    """Comment for a quiz"""
    quiz = models.ForeignKey(
        Quiz,
        on_delete=models.CASCADE,
        verbose_name='Викторина',
        related_name='comments'
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        verbose_name='Автор',
        related_name='comments'
    )
    body = models.TextField('Текст')
    date = models.DateTimeField(
        'Дата создания',
        auto_now_add=True
    )

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ['-date']

    def __str__(self):
        return self.body


class Bookmark(models.Model):
    """Bookmar for a quiz"""
    quiz = models.ForeignKey(
        Quiz,
        on_delete=models.CASCADE,
        verbose_name='Викторина',
        related_name='bookmarks'
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name='Пользователь',
        related_name='bookmarks'
    )
    date = models.DateTimeField(
        'Дата добавления',
        auto_now_add=True
    )

    class Meta:
        verbose_name = 'Закладка'
        verbose_name_plural = 'Закладки'
        ordering = ['-date']

    def __str__(self):
        return f'{self.user} - {self.quiz}'


class Question(models.Model):

src/quizapp/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Quiz, Comment


class QuizCreateForm(forms.ModelForm):
    """Form for create a quiz"""
    class Meta:
        model = Quiz
        fields = ['title', 'body', 'level', 'category', 'photo']


class CommentCreateForm(forms.ModelForm):
    """Form for create a quiz comment"""
    class Meta:
        model = Comment
        fields = ['body']

        widgets = {
            'body': forms.Textarea(attrs={'cols': 100, 'rows': 1,
                                'class': 'comment_create_body'})
        }

        labels = {
            'body': 'Комментарий'
        }

src/quizapp/templates/quizapp/home.html
{% extends 'base.html' %}

{% load static %}
{% load humanize %}
{% load crispy_forms_tags %}

{% block title %}Главная{% endblock %}

{% block links %}
<link rel="stylesheet" href="{% static 'css/style.css' %}" />
{% endblock %}

{% block content %}
<div class="container">
  <div class="row">

    <!-- Left column. The quizzes -->
    <div class="col-lg-8 col-sm-12">

      {% for quiz in quizzes %}
      <div class="quiz">
        <div class="quiz__usertitle-wrap">
          <h4 class="quiz__title mb-4">{{ quiz.title }}</h4>

          <div class="quiz__user">
            <!-- Manage list ul -->
            <div class="user__manage">
              <i class="fas fa-ellipsis-h mr-3 manage__menu"></i>

              <ul class="manage__list">
                {% if user == quiz.author or user.is_staff %}
                <a href="{{ quiz.get_update_url }}" class="list__item">
                  <i class="fas fa-pencil-alt"></i>
                  <span class="item__span">Править</span>
                </a>

                <a href="#" data-slug="{{ quiz.slug }}" class="list__item list__item_delete">
                  <i class="fas fa-trash"></i>
                  <span class="item__span">Удалить</span>
                </a>
                {% endif %}

                <a href="#" class="list__item list__item_link">
                  <i class="fas fa-link"></i>
                  <span class="item__span">Копировать ссылку</span>
                  <p class="link__p">
                    {{ current_url }}quiz/{{ quiz.slug}}
                  </p>
                </a>
              </ul>
            </div>
            <!-- End of the manage list -->

            <img src="{{ quiz.author.profile.photo.url }}" class="user__img" alt="Photo" />
            <span class="user__username">{{ quiz.author.username }}</span>
          </div>
        </div>

        <span class="quiz__views quiz__views-home pr-2">
          <small>
            <i class="far fa-eye fa-eye-home"></i> {{ quiz.views|intcomma }}
          </small> </span>|
        <span class="quiz__date quiz__date-home">
          <small>{{ quiz.date|naturaltime }}</small> </span><br />

        <p class="quiz__body">
          {% if quiz.body|length > 150 %} {{ quiz.body|slice:':150' }}...<br />
          <a href="{{ quiz.get_absolute_url }}">
            <small>Читать полностью</small>
          </a>
          {% else %} {{ quiz.body }} {% endif %}
        </p>

        {% if quiz.photo %}
        <img src="{{ quiz.photo.url }}" class="quiz__photo" alt="Photo" />
        {% endif %}

        <button type="button" class="quiz__level btn
        {% if quiz.level == 'Легко' %}btn-success{% endif %}
        {% if quiz.level == 'Средне' %}btn-primary{% endif %}
        {% if quiz.level == 'Сложно' %}btn-hard{% endif %}
        {% if quiz.level == 'Экстремально' %}btn-danger{% endif %}
        ">
          {{ quiz.level }}
        </button>

        {% if quiz.category %}
        <button class="btn quiz__category">{{ quiz.category }}</button>
        {% endif %}

        <p class="quiz__parameters">
          <span class="quiz__likes">
            <i class="{% if user in quiz.likes.all %}liked-heart fas{% else %}
            far{% endif %} fa-heart quiz__likes_icon" data-slug="{{ quiz.slug }}"></i>
            <span class="quiz__likes_count">
              {{ quiz.get_likes_count|intcomma }}
            </span>
          </span>

          <span class="quiz__comments ml-3">
            <i class="far fa-comment"></i>
            <span class="quiz__comments_count">
              {{ quiz.get_comments_count }}
            </span>
          </span>

          <span class="quiz__bookmarks ml-3">
            <i class="fa-star quiz__bookmarks_icon
            {% if user.id in quiz.get_bookmarks_users %}fas bookmarked{% else %}
            far{% endif %}" data-slug="{{ quiz.slug }}"></i>
            <span class="quiz__bookmarks_count">
              {{ quiz.get_bookmarks_count }}
            </span>
          </span>
        </p>

        <a href="{{ quiz.get_absolute_url }}" class="mt-2 btn btn-join btn-block">
          Пройти
        </a>
      </div>
      {% endfor %}

      <!-- Pagination -->
      {% if is_paginated %}
      <nav>
        <ul class="pagination">
          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page=1">
              &laquo;
            </a>
          </li>

          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
              &lt;
            </a>
          </li>
          {% endif %}

          {% for n in page_obj.paginator.page_range %}
          {% if n > page_obj.number|add:-4 and n < page_obj.number|add:4 %}
          <li class="page-item">
            <a class="page-link {% if n == page_obj.number %}
                      active-pagination {% else %}no-active {% endif %}" href="?page={{ n }}">{{ n }}</a>
          </li>
          {% endif %}
          {% endfor %}

          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
              &gt;
            </a>
          </li>

          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
              &raquo;
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}
      <!-- End of the pagination -->

    </div>
    <!-- End of the left column -->


    <!-- Right column of the filters -->
    <div class="col-lg-4 filter-col">
      <div class="filter-column">

        <div class="filter">

          <form method="GET" class="filter__form">
            {{ filter_form|crispy }}
            <input type="submit" class="btn btn-join" value="Найти" />
          </form>

        </div>

        <div class="filter__links">

          <a class="links__link {% if active == 'most_viewed' %}link__active{% endif %}" href="{% url 'most-viewed' %}">
            <img class="link__img" src="{% static 'img/graph.png' %}" alt="Graph">
            Популярное
          </a>
          <a class="links__link {% if active == 'most_liked' %}link__active{% endif %}" href="{% url 'most-liked' %}">
            <img class="link__img" src="{% static 'img/fire.png' %}" alt="Fire">
            Лучшее
          </a>

        </div>

      </div>
    </div>
    <!-- End of the right column -->


    <!-- Modal for delete a quiz -->
    <div class="modal">
      <div class="modal-content">
        <div class="modal__header">
          <span class="modal__close">x</span>
          <h5>Вы действительно хотите удалить викторину?</h5>
        </div>

        <div class="modal-body">
          <form id="delete__form" method="POST">
            {% csrf_token %}
            <button class="btn btn-join modal__btn_delete" type="submit">
              Удалить
            </button>
          </form>
        </div>
      </div>
    </div>
    <!-- End modal -->
  </div>
</div>
{% endblock %}

{% block js %}
<script src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<script src="{% static 'js/manageQuizMenu.js' %}"></script>
<script src="{% static 'js/deleteQuiz.js' %}"></script>
<script src="{% static 'js/copyQuizLink.js' %}"></script>
<script src="{% static 'js/quizLike.js' %}"></script>
<script src="{% static 'js/quizBookmark.js' %}"></script>
{% endblock %}

src/quizapp/templates/quizapp/quiz_create.html
{% extends 'base.html' %}

{% load static %}
{% load humanize %}
{% load crispy_forms_tags %}

{% block title %}Создать викторину{% endblock %}

{% block links %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block content %}

<div class="container">
  <div class="row">
    <div class="col-lg-9 col-sm-12 quiz-create">

      <form method="post" class="quiz-create__form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="quiz-create__btn-wrap">
          <input class="btn btn-join quiz-create__btn"
          type="submit" value="Создать">
        </div>
      </form>

    </div>
  </div>
</div>

{% endblock %}

src/quizapp/templates/quizapp/quiz_detail.html
{% extends 'base.html' %}

{% load static %}
{% load humanize %}
{% load crispy_forms_tags %}

{% block title %}{{ quiz.title }}{% endblock %}

{% block links %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block content %}
<div class="container detail-container">

  <!-- Quiz detail section -->
  <section class="quiz-detail">
    <div class="row">

      <!-- left column -->
      <div class="col-lg-9 col-sm-12 quiz-detail__left-wrap">

        <h3 class="quiz-detail__title">{{ quiz.title }}</h3>
        <h4 class="quiz-detail__body mb-3">{{ quiz.body|linebreaks }}</h4>

        {% if quiz.photo %}
        <img src="{{ quiz.photo.url }}" class="quiz-detail__photo" alt="Photo">
        {% endif %}

        <button class="btn quiz__level mb-3
        {% if quiz.level == 'Легко' %}btn-success{% endif %}
        {% if quiz.level == 'Средне' %}btn-primary{% endif %}
        {% if quiz.level == 'Сложно' %}btn-hard{% endif %}
        {% if quiz.level == 'Экстремально' %}btn-danger{% endif %}">
          {{ quiz.level }}
        </button>

        {% if quiz.category %}
        <button class="btn quiz__category mb-3">{{ quiz.category }}</button>
        {% endif %}

        <br>
        <span class="quiz__likes quiz__likes-detail mt-4">
          <i class="{% if user in quiz.likes.all %}liked-heart fas{% else %}
          far{% endif %} fa-heart quiz__likes_icon" data-slug="{{ quiz.slug }}"></i>
          <span class="quiz__likes_count">
            {{ quiz.get_likes_count|intcomma }}
          </span>
        </span>

        <span class="quiz__comments quiz__comments-detail ml-3">
          <i class="far fa-comment"></i> {{ quiz.get_comments_count }}
        </span>

        <span class="quiz__bookmarks ml-3">
          <i class="fa-star quiz__bookmarks_icon
          {% if user.id in quiz.get_bookmarks_users %}fas bookmarked{% else %}
          far{% endif %}" data-slug="{{ quiz.slug }}"></i>
          <span class="quiz__bookmarks_count">
            {{ quiz.get_bookmarks_count }}
          </span>
        </span>

        <div class="quiz-detail__btn-start">
          <a href="{{ quiz.get_question_list_url }}" class="btn btn-join btn-start">Начать</a>
        </div>

        <!-- Comments section -->
        <section class="comments">
          {% if user.is_authenticated %}
          <form class="comments__form" data-slug="{{ quiz.slug }}" method="post">
            {% csrf_token %}
            <div class="form__wrap">
              {{ form|crispy }}
              <button type="submit" class="form__btn">
                <i class="fas fa-paper-plane form__submit"></i>
              </button>
            </div>
          </form>
          {% else %}
          <a href="#">Зарегистрируйтесь, чтобы написать комментарий</a>
          {% endif %}

          <div class="comment__objects">
            {% for comment in quiz.comments.all %}
            <div class="comment">

              <hr>
              <div class="comment__username-wrap">
                <div class="user">
                  <img class="user__img" src="/static/img/testuser.png" alt="Photo">
                  <span class="user__username">{{ comment.author.username }}</span>
                </div>

                <p class="comment__date">{{ comment.date|naturaltime }}</p>

                {% if user == comment.author or user.is_staff %}
                <form id="delete__form" method="POST" data-pk="{{ comment.pk }}">
                  {% csrf_token %}
                  <button type="submit" class="date-delete__delete">
                    <i class="fas fa-trash"></i>
                    </a>
                </form>
                {% endif %}
              </div>

              <p class="comment__body">{{ comment.body }}</p>

            </div>
            {% endfor %}
          </div>
        </section>
        <!-- End comments section -->

      </div>
      <!-- End left column -->

      <!-- Right column -->
      <div class="col-lg-3 quiz-detail__right-wrap">

        <img src="/static/img/testuser.png" class="user__img" alt="Photo">
        <span class="user__username">{{ quiz.author.username }}</span><br>

        <span class="quiz__views quiz__views_detail mt-4" title="Просмотры">
          <i class="far fa-eye mr-1"></i> {{ quiz.views }}
        </span><br>

        <span class="quiz__date quiz__date_detail mt-1" title="Дата">
          <i class="far fa-clock"></i> {{ quiz.date|naturaltime }}
        </span>

        <p class="quiz__completed mt-4">
          Пройдено: {{ quiz.get_completed_count }}<br>
          Вопросов: {{ quiz.get_questions_count }}
        </p>

        {% if quiz.author == user %}
        <div class="manage_buttons">
          <div class="btns_string">
            <a href="{{ quiz.get_update_url }}" class="btn btn-join manage_buttons__btn">Править</a>
            <a href="#" data-slug="{{ quiz.slug }}" class="btn btn-join list__item_delete manage_buttons__btn">
              <span class="item__span">Удалить</span>
            </a>
          </div>

          <a href="{{ quiz.get_manage_questions_url }}" class="btn btn-join btn-block btn-add">
            Управление вопросами
          </a>
        </div>
        {% endif %}

      </div>
      <!-- End right column -->

    </div>

    <!-- Modal for delete a quiz -->
    <div class="modal">
      <div class="modal-content">
        <div class="modal__header">
          <span class="modal__close">x</span>
          <h5>Вы действительно хотите удалить викторину?</h5>
        </div>

        <div class="modal-body">
          <form id="delete__form" method="POST">
            {% csrf_token %}
            <button class="btn btn-join modal__btn_delete" type="submit">
              Удалить
            </button>
          </form>
        </div>
      </div>
    </div>
    <!-- End modal -->

  </section>

</div>
{% endblock %}

{% block js %}
<script src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<script src="{% static 'js/deleteQuiz.js' %}"></script>
<script>
  $(document).on('submit', '.comments__form', function (e) {
    e.preventDefault();

    $.ajax({
      type: 'POST',
      url: '{% url "comment-create-api" quiz.slug %}',
      data: {
        body: $('#id_body').val(),
        csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
      },
      success: function (data) {
        let quizBlock = document.createElement('div');
        document.querySelector('#id_body').value = ' ';
        quizBlock.classList.add('comment');

        quizBlock.innerHTML = `
                <hr>
                <div class="comment__username-wrap">
                  <div class="user">
                    <img class="user__img" src="/static/img/testuser.png" alt="Photo">
                    <span class="user__username">{{ user.username }}</span>
                  </div>

                  <p class="comment__date">сейчас</p>
                </div>

                <p class="comment__body">${data.body}</p>
              `;
        $('.comment__objects').prepend(quizBlock);
      },
      error: function (err) {
        console.log(err);
      }
    });
  })
</script>
<script src="{% static 'js/deleteComment.js' %}"></script>
<script src="{% static 'js/quizLike.js' %}"></script>
<script src="{% static 'js/quizBookmark.js' %}"></script>
{% endblock %}